linters:

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - copyloopvar
    - dupword
    - errcheck
    - exhaustive
    - gci
    - gocritic
    - godot
    - gofmt
    - gosec
    - govet
    - ineffassign
    - intrange
    - lll
    - misspell
    - nonamedreturns
    - revive
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - whitespace
    - wsl

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  revive:
    rules:
      - name: early-return
        disabled: false
      - name: import-shadowing
        disabled: false
      - name: exported
        arguments:
          - sayRepetitiveInsteadOfStutters
          - checkPublicInterface
  wsl:
    allow-cuddle-declarations: true

issues:
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment.
    - EXC0013  # EXC0012 revive: Annoying issue about not having a comment.
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment.

  exclude-rules:
    - path: internal/...
      linters:
        - revive
      text: "^exported"